import {
  ArrowLeft,
  ArrowRight,
  Bell,
  Briefcase,
  Building,
  Calendar,
  CalendarDays,
  Car,
  Check,
  CheckCircle,
  ChevronRight,
  Circle,
  Clock,
  Compass,
  DollarSign,
  ExternalLink,
  File,
  FileText,
  Folder,
  Globe,
  HeartPulse,
  LayoutDashboard,
  ListChecks,
  Map,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  NotebookPen,
  Pencil,
  Plane,
  Plus,
  Receipt,
  Save,
  Search,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Ticket,
  Trash2,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wifi,
  X,
} from 'lucide-react';

const ICONS = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bell: Bell,
  trips: Briefcase,
  hotel: Building,
  building: Building,
  calendar: Calendar,
  calendarDays: CalendarDays,
  car: Car,
  check: Check,
  checkCircle: CheckCircle,
  chevronRight: ChevronRight,
  circle: Circle,
  clock: Clock,
  explore: Compass,
  money: DollarSign,
  externalLink: ExternalLink,
  file: File,
  notes: FileText,
  folder: Folder,
  globe: Globe,
  heartPulse: HeartPulse,
  dashboard: LayoutDashboard,
  checklist: ListChecks,
  map: Map,
  pin: MapPin,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  more: MoreHorizontal,
  notebook: NotebookPen,
  edit: Pencil,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  save: Save,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  ticket: Ticket,
  trash: Trash2,
  userRound: UserRound,
  users: Users,
  food: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  close: X,
};

export function Icon({ name, size = 20, strokeWidth = 1.9, ...props }) {
  const IconComponent = ICONS[name] || Sparkles;
  return <IconComponent aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
}
