import {
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  Bike,
  Bus,
  Bell,
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  Briefcase,
  Building,
  Calendar,
  CalendarDays,
  CalendarRange,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSun,
  Car,
  Check,
  CheckCircle,
  BarChart3,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Compass,
  Copy,
  DollarSign,
  Download,
  Footprints,
  Droplets,
  ExternalLink,
  File,
  FileText,
  Folder,
  Globe,
  Info,
  HeartPulse,
  LayoutDashboard,
  ListChecks,
  Map,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MessageCircle,
  MoreHorizontal,
  Pin,
  PinOff,
  Printer,
  NotebookPen,
  Pencil,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  Route,
  Save,
  Send,
  Share2,
  Search,
  Snowflake,
  Settings,
  Shield,
  Sparkles,
  Star,
  Sun,
  Ticket,
  Upload,
  Undo2,
  UserMinus,
  UserPlus,
  Trash2,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Eye,
  X,
} from 'lucide-react';

const ICONS = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  activity: Activity,
  exchange: ArrowRightLeft,
  bike: Bike,
  bus: Bus,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  archive: Archive,
  restore: ArchiveRestore,
  bell: Bell,
  trips: Briefcase,
  hotel: Building,
  building: Building,
  calendar: Calendar,
  calendarDays: CalendarDays,
  calendarRange: CalendarRange,
  cloud: Cloud,
  cloudLightning: CloudLightning,
  cloudRain: CloudRain,
  cloudSun: CloudSun,
  car: Car,
  check: Check,
  checkCircle: CheckCircle,
  chart: BarChart3,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clock: Clock,
  explore: Compass,
  copy: Copy,
  money: DollarSign,
  download: Download,
  walk: Footprints,
  droplets: Droplets,
  externalLink: ExternalLink,
  file: File,
  notes: FileText,
  folder: Folder,
  globe: Globe,
  info: Info,
  heartPulse: HeartPulse,
  dashboard: LayoutDashboard,
  checklist: ListChecks,
  map: Map,
  pin: MapPin,
  menu: Menu,
  monitor: Monitor,
  moon: Moon,
  message: MessageCircle,
  more: MoreHorizontal,
  pinTrip: Pin,
  pinOff: PinOff,
  print: Printer,
  notebook: NotebookPen,
  edit: Pencil,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  refresh: RefreshCw,
  route: Route,
  save: Save,
  send: Send,
  share: Share2,
  search: Search,
  snowflake: Snowflake,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  ticket: Ticket,
  upload: Upload,
  undo: Undo2,
  userMinus: UserMinus,
  userPlus: UserPlus,
  trash: Trash2,
  userRound: UserRound,
  users: Users,
  food: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  eye: Eye,
  close: X,
};

export function Icon({ name, size = 20, strokeWidth = 1.9, ...props }) {
  const IconComponent = ICONS[name] || Sparkles;
  return <IconComponent aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
}
